// src/components/ai-analysis/AIExplanation.jsx

import React from 'react';
import { Brain, Lightbulb, MessageCircle } from 'lucide-react';

const AIExplanation = ({ explanation, recommendation }) => {
  // Get color based on recommendation
  const getRecommendationColor = () => {
    if (recommendation.includes('Buy')) {
      return {
        bg: 'from-green-600 to-emerald-600',
        lightBg: 'bg-green-50',
        border: 'border-green-200',
        text: 'text-green-600',
      };
    } else if (recommendation === 'Hold') {
      return {
        bg: 'from-yellow-600 to-orange-600',
        lightBg: 'bg-yellow-50',
        border: 'border-yellow-200',
        text: 'text-yellow-600',
      };
    } else {
      return {
        bg: 'from-red-600 to-pink-600',
        lightBg: 'bg-red-50',
        border: 'border-red-200',
        text: 'text-red-600',
      };
    }
  };

  const colors = getRecommendationColor();

  return (
    <div className={`${colors.lightBg} rounded-xl p-6 border-2 ${colors.border}`}>
      {/* Header */}
      <div className="flex items-center space-x-3 mb-6">
        <div className={`bg-gradient-to-r ${colors.bg} p-3 rounded-xl`}>
          <Brain className="text-white" size={24} />
        </div>
        <div>
          <h3 className="text-xl font-bold text-gray-900">AI Explanation</h3>
          <p className="text-sm text-gray-600">Why {recommendation}?</p>
        </div>
      </div>

      {/* Explanation Box */}
      <div className="bg-white rounded-lg p-5 shadow-sm border border-gray-200 mb-4">
        <div className="flex items-start space-x-3">
          <div className={`${colors.lightBg} p-2 rounded-lg flex-shrink-0 mt-1`}>
            <MessageCircle className={colors.text} size={20} />
          </div>
          <p className="text-gray-700 leading-relaxed text-base">
            {explanation}
          </p>
        </div>
      </div>

      {/* Key Insight Badge */}
      <div className="flex items-center justify-center">
        <div className={`${colors.lightBg} border ${colors.border} rounded-full px-4 py-2 flex items-center space-x-2`}>
          <Lightbulb className={colors.text} size={16} />
          <span className={`text-sm font-semibold ${colors.text}`}>
            AI-Generated Insight
          </span>
        </div>
      </div>

      {/* Bottom Info */}
      <div className="mt-4 pt-4 border-t border-gray-200">
        <p className="text-xs text-gray-500 text-center">
          This explanation is generated by analyzing multiple factors including fundamentals, 
          technicals, market sentiment, and historical patterns.
        </p>
      </div>
    </div>
  );
};

export default AIExplanation;