import { AlertTriangle, Shield, TrendingDown, BookOpen, FileText, AlertCircle } from 'lucide-react';

function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-yellow-50 via-orange-50 to-red-50 py-12">
      <div className="max-w-4xl mx-auto px-6">
        {/* Warning Banner */}
        <div className="bg-gradient-to-r from-red-600 to-orange-600 text-white rounded-xl shadow-2xl p-8 mb-8">
          <div className="flex items-center space-x-4 mb-4">
            <AlertTriangle size={48} />
            <div>
              <h1 className="text-4xl font-bold">Important Disclaimer</h1>
              <p className="text-red-100 mt-2">Please read carefully before using this platform</p>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="bg-white rounded-xl shadow-lg p-8">
          <div className="prose prose-lg max-w-none">
            {/* Introduction */}
            <section className="mb-10">
              <div className="flex items-center space-x-3 mb-4">
                <FileText className="text-red-600" size={32} />
                <h2 className="text-3xl font-bold text-gray-900 mb-0">Legal Disclaimer</h2>
              </div>
              <p className="text-gray-700 text-lg leading-relaxed">
                <strong>Last Updated:</strong> November 2024
              </p>
              <p className="text-gray-700 text-lg leading-relaxed mt-4">
                This disclaimer governs your use of Spark Investment AI. By accessing or using our platform,
                you acknowledge that you have read, understood, and agreed to be bound by this disclaimer.
              </p>
            </section>

            {/* Not Investment Advice */}
            <section className="mb-10 bg-red-50 border-l-4 border-red-500 p-6 rounded-r-lg">
              <div className="flex items-center space-x-3 mb-4">
                <AlertCircle className="text-red-600" size={28} />
                <h2 className="text-2xl font-bold text-red-900 mb-0">1. Not Investment Advice</h2>
              </div>
              <div className="text-gray-800 space-y-4">
                <p>
                  <strong className="text-red-700">Spark Investment AI is NOT an investment advisor.</strong> We do not
                  provide investment advice, recommendations, or trading services. All information, analysis,
                  predictions, and insights provided by this platform are:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>For <strong>educational and informational purposes only</strong></li>
                  <li>Generated by automated algorithms and AI models</li>
                  <li>Based on historical data and statistical analysis</li>
                  <li>NOT personalized financial advice</li>
                  <li>NOT recommendations to buy, sell, or hold any securities</li>
                </ul>
                <p className="bg-red-100 border border-red-300 rounded-lg p-4 mt-4">
                  <strong className="text-red-800">⚠️ Critical Warning:</strong> You should NEVER make investment
                  decisions based solely on information from this platform. Always consult with a qualified,
                  SEBI-registered investment advisor before making any financial decisions.
                </p>
              </div>
            </section>

            {/* Not SEBI Registered */}
            <section className="mb-10">
              <div className="flex items-center space-x-3 mb-4">
                <Shield className="text-orange-600" size={28} />
                <h2 className="text-2xl font-bold text-gray-800 mb-0">2. Not SEBI Registered</h2>
              </div>
              <p className="text-gray-700 mb-4">
                Spark Investment AI is <strong>NOT registered</strong> with SEBI (Securities and Exchange Board
                of India) as:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4">
                <li>Investment Advisor (IA)</li>
                <li>Research Analyst (RA)</li>
                <li>Stock Broker</li>
                <li>Portfolio Manager</li>
                <li>Mutual Fund Distributor</li>
              </ul>
              <p className="text-gray-700">
                We are a technology platform providing portfolio tracking tools and analytics. We do not:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mt-2">
                <li>Accept deposits or funds from users</li>
                <li>Execute trades on behalf of users</li>
                <li>Manage portfolios</li>
                <li>Provide personalized investment recommendations</li>
                <li>Distribute financial products</li>
              </ul>
            </section>

            {/* Risk Warning */}
            <section className="mb-10 bg-yellow-50 border-l-4 border-yellow-500 p-6 rounded-r-lg">
              <div className="flex items-center space-x-3 mb-4">
                <TrendingDown className="text-yellow-700" size={28} />
                <h2 className="text-2xl font-bold text-yellow-900 mb-0">3. Investment Risks</h2>
              </div>
              <div className="text-gray-800 space-y-4">
                <p>
                  <strong className="text-yellow-800">Investing involves substantial risk.</strong> You acknowledge
                  and accept that:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>You may lose some or <strong>all of your invested capital</strong></li>
                  <li>Past performance does NOT guarantee future results</li>
                  <li>Stock markets are volatile and unpredictable</li>
                  <li>AI predictions and analysis can be wrong</li>
                  <li>No investment strategy guarantees profits</li>
                  <li>Tax implications may affect your returns</li>
                  <li>Market conditions can change rapidly</li>
                </ul>
                <p className="bg-yellow-100 border border-yellow-300 rounded-lg p-4 mt-4">
                  <strong className="text-yellow-800">Risk Tolerance:</strong> Only invest money you can afford to
                  lose. Consider your financial situation, risk tolerance, and investment goals before investing.
                </p>
              </div>
            </section>

            {/* User Responsibility */}
            <section className="mb-10">
              <div className="flex items-center space-x-3 mb-4">
                <BookOpen className="text-indigo-600" size={28} />
                <h2 className="text-2xl font-bold text-gray-800 mb-0">4. Your Responsibility</h2>
              </div>
              <p className="text-gray-700 mb-4">
                You are <strong>solely responsible</strong> for all investment decisions you make. By using
                this platform, you agree that:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4">
                <li>You will conduct your own due diligence and research</li>
                <li>You will consult with qualified professionals (financial advisors, tax consultants, lawyers)</li>
                <li>You understand the risks involved in trading and investing</li>
                <li>You will not rely solely on platform data for investment decisions</li>
                <li>You will verify all data and information independently</li>
                <li>You will comply with all applicable laws and regulations</li>
                <li>You will not hold Spark Investment AI liable for any losses</li>
              </ul>
            </section>

            {/* No Guarantees */}
            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">5. No Guarantees or Warranties</h2>
              <p className="text-gray-700 mb-4">
                Spark Investment AI provides this platform "AS IS" without any warranties:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mb-4">
                <li>
                  <strong>No Accuracy Guarantee:</strong> We do not guarantee the accuracy, completeness, or
                  timeliness of any data, analysis, or predictions
                </li>
                <li>
                  <strong>No Performance Guarantee:</strong> Past performance shown on the platform does not
                  guarantee future results
                </li>
                <li>
                  <strong>No Profit Guarantee:</strong> AI recommendations and strategies do not guarantee
                  profits or protect against losses
                </li>
                <li>
                  <strong>Technical Issues:</strong> The platform may experience downtime, errors, or technical
                  issues beyond our control
                </li>
                <li>
                  <strong>Data Delays:</strong> Market data may be delayed or inaccurate due to third-party
                  data providers
                </li>
              </ul>
            </section>

            {/* Third-Party Platforms */}
            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">6. Third-Party Trading Platforms</h2>
              <p className="text-gray-700 mb-4">
                Spark Investment AI integrates with third-party trading platforms (Zerodha, Groww, Upstox, etc.)
                for data aggregation purposes only:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                <li>We do NOT execute trades on your behalf</li>
                <li>You are responsible for all transactions made on these platforms</li>
                <li>We are not affiliated with, endorsed by, or responsible for these third-party platforms</li>
                <li>These platforms have their own terms of service and privacy policies</li>
                <li>We do not guarantee the security or reliability of third-party integrations</li>
              </ul>
            </section>

            {/* Limitation of Liability */}
            <section className="mb-10 bg-gray-50 border-l-4 border-gray-400 p-6 rounded-r-lg">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">7. Limitation of Liability</h2>
              <div className="text-gray-700 space-y-4">
                <p>
                  <strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</strong>
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    Spark Investment AI, its founders, employees, and affiliates shall NOT be liable for any
                    direct, indirect, incidental, consequential, or punitive damages arising from your use of
                    the platform
                  </li>
                  <li>This includes but is not limited to: financial losses, lost profits, trading losses,
                    data loss, or business interruption
                  </li>
                  <li>We are not responsible for losses resulting from reliance on platform information</li>
                  <li>We are not liable for errors, omissions, or inaccuracies in data or analysis</li>
                </ul>
                <p className="bg-gray-100 border border-gray-300 rounded-lg p-4 mt-4">
                  <strong>Maximum Liability:</strong> In no event shall our total liability exceed ₹1,000 (one
                  thousand rupees) or the amount you paid to use the platform in the past 12 months, whichever
                  is lower.
                </p>
              </div>
            </section>

            {/* Regulatory Compliance */}
            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">8. Regulatory Compliance</h2>
              <p className="text-gray-700 mb-4">
                You are responsible for complying with all applicable laws and regulations, including:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                <li>SEBI regulations and guidelines</li>
                <li>Income Tax Act, 1961 (for capital gains, dividends, etc.)</li>
                <li>Foreign Exchange Management Act (FEMA) for international investments</li>
                <li>Prevention of Money Laundering Act (PMLA)</li>
                <li>Any other applicable Indian financial regulations</li>
              </ul>
            </section>

            {/* Professional Advice */}
            <section className="mb-10 bg-indigo-50 border-l-4 border-indigo-500 p-6 rounded-r-lg">
              <h2 className="text-2xl font-bold text-indigo-900 mb-4">9. Seek Professional Advice</h2>
              <p className="text-gray-800 mb-4">
                <strong className="text-indigo-700">We strongly recommend</strong> that you consult with
                qualified professionals before making any financial decisions:
              </p>
              <ul className="list-disc list-inside text-gray-800 space-y-2 ml-4">
                <li>
                  <strong>SEBI-Registered Investment Advisor:</strong> For personalized investment advice
                </li>
                <li>
                  <strong>Chartered Accountant (CA):</strong> For tax planning and implications
                </li>
                <li>
                  <strong>Financial Planner:</strong> For comprehensive financial planning
                </li>
                <li>
                  <strong>Legal Advisor:</strong> For legal and regulatory compliance
                </li>
              </ul>
            </section>

            {/* Changes to Disclaimer */}
            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">10. Changes to This Disclaimer</h2>
              <p className="text-gray-700">
                We reserve the right to modify this disclaimer at any time. Changes will be effective
                immediately upon posting to the platform. Your continued use of the platform after any changes
                constitutes acceptance of the modified disclaimer. We recommend reviewing this page periodically.
              </p>
            </section>

            {/* Contact Information */}
            <section className="mb-10">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">11. Questions or Concerns</h2>
              <p className="text-gray-700 mb-4">
                If you have any questions about this disclaimer, please review our:
              </p>
              <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                <li>
                  <a href="/terms" className="text-indigo-600 hover:text-indigo-800 font-semibold">
                    Terms of Service
                  </a>
                </li>
                <li>
                  <a href="/privacy" className="text-indigo-600 hover:text-indigo-800 font-semibold">
                    Privacy Policy
                  </a>
                </li>
              </ul>
            </section>

            {/* Final Warning */}
            <section className="bg-red-100 border-2 border-red-500 rounded-xl p-6 mt-10">
              <div className="flex items-start space-x-4">
                <AlertTriangle className="text-red-600 flex-shrink-0 mt-1" size={32} />
                <div>
                  <h3 className="text-xl font-bold text-red-900 mb-3">Final Warning</h3>
                  <p className="text-red-800 mb-3">
                    By using Spark Investment AI, you explicitly acknowledge and agree that:
                  </p>
                  <ul className="list-disc list-inside text-red-800 space-y-2">
                    <li>You have read and understood this entire disclaimer</li>
                    <li>You accept all risks associated with investing</li>
                    <li>You will not hold us liable for any losses or damages</li>
                    <li>You are using this platform at your own risk</li>
                    <li>You will seek professional advice before making investment decisions</li>
                  </ul>
                  <p className="text-red-900 font-bold mt-4 text-lg">
                    IF YOU DO NOT AGREE WITH THIS DISCLAIMER, DO NOT USE THIS PLATFORM.
                  </p>
                </div>
              </div>
            </section>
          </div>
        </div>

        {/* Back to Home */}
        <div className="text-center mt-8">
          <a
            href="/"
            className="inline-block px-8 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-lg hover:from-indigo-700 hover:to-purple-700 transition-all shadow-md hover:shadow-lg"
          >
            Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}

export default DisclaimerPage;
